apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgdeployment
  name: bgdeployment
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: practicedep
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: practicedep
        version: v1
    spec:
      containers:
      - image: nginx:1.14.1
        imagePullPolicy: IfNotPresent
        name: nginx
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgservice 
  name: bgservice
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: practicedep
    version: v1
  type: ClusterIP
