apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgservice 
  name: bgservice
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: practicedep
    version: v1
  type: ClusterIP
