apiVersion: v1
kind: Service
metadata:
  labels:
    app: newbgservice 
  name: newbgservice
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: practicedep
    version: v2
  type: ClusterIP
